version: '3.8'

services:
  db:
    image: bitnami/postgresql
    environment:
      POSTGRES_USER: squall
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nodesolid
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
